import type { SiteContent } from "../types";

export const features: SiteContent["features"] = {
  metaTitle: "Fonctionnalités — tout le produit sur une page",
  metaDescription:
    "Neuf modules, un seul modèle de données : comptabilité et annexes, appels de fonds, assemblées générales, dépenses, résidents, gardien, location courte durée, portefeuille.",
  crumb: "FONCTIONNALITÉS",
  title: "Tout le produit sur une page.",
  lede: "Neuf domaines, un seul modèle de données. Une dépense saisie par le gardien devient une ligne d'annexe, un point d'ordre du jour et une quote-part sur la quittance d'un lot — sans que personne ne la retape.",
  image: "/images/residence-hero.jpg",
  imageAlt: "Résidence en copropriété gérée avec SyndicUp",
  cards: [
    {
      href: "/comptabilite-annexes",
      icon: "annexes",
      title: "Comptabilité & annexes",
      desc: "Les 12 annexes du Décret 2.23.700, produites depuis vos écritures. Le cœur du produit.",
      badge: "PAGE PILIER",
    },
    {
      href: "/appels-de-fonds-recouvrement",
      icon: "appels",
      title: "Appels de fonds & recouvrement",
      desc: "Répartition aux tantièmes, quittances numérotées, relances graduées, échéanciers.",
    },
    {
      href: "/assemblees-generales",
      icon: "ag",
      title: "Assemblées générales",
      desc: "Convocation tracée, quorum calculé, pouvoirs plafonnés, votes par tantièmes, PV horodaté.",
    },
    {
      href: "/depenses-justificatifs",
      icon: "depenses",
      title: "Dépenses & justificatifs",
      desc: "Aucune dépense n'entre en comptabilité sans sa facture. File de validation à deux yeux.",
    },
    {
      href: "/application-residents",
      icon: "residents",
      title: "Application résidents",
      desc: "Solde, quittances, incidents avec photo, documents, comptes de la résidence. FR & AR.",
    },
    {
      href: "/gardien-et-loge",
      icon: "gardien",
      title: "Gardien & loge",
      desc: "Incidents en photo, rondes horodatées, petite caisse, relevés de compteurs.",
    },
    {
      href: "/location-courte-duree",
      icon: "lcd",
      title: "Location courte durée",
      desc: "Séjours déclarés, quote-part eau et déchets recalculée, registre des occupants.",
      badge: "UNIQUE SUR LE MARCHÉ",
    },
    {
      href: "/multi-residences-cabinets",
      icon: "multi",
      title: "Multi-résidences & cabinets",
      desc: "Un portefeuille, un écran de pilotage, des permissions par gestionnaire.",
    },
  ],
  modulesKicker: "NEUF MODULES",
  modulesTitle: "Un module par métier, une seule base.",
  modulesLede: "Chaque module est une page : ce qu'il règle, comment il marche, pour qui, et ce qu'il ne fait pas.",
  flowKicker: "LE FIL ROUGE",
  flowTitle: "Une donnée entre une fois. Elle ressort partout.",
  flowLede: "Suivez une facture d'ascenseur : c'est le trajet que fait chaque dirham dans le produit.",
  flow: [
    { icon: "mobile", title: "Le gardien la photographie", desc: "À la loge, depuis un téléphone d'entrée de gamme. La pièce existe avant le montant." },
    { icon: "review", title: "Le syndic la valide", desc: "Dans la file, seul sous le seuil voté, à deux yeux au-dessus." },
    { icon: "bank", title: "Elle devient une charge", desc: "Répartie aux tantièmes, clé ascenseur, au centime — l'écart d'arrondi attribué." },
    { icon: "excel", title: "Elle entre dans l'annexe", desc: "État des dépenses, répartition par lot : générés, pas ressaisis." },
    { icon: "sms", title: "Le copropriétaire la voit", desc: "Depuis sa quote-part jusqu'à la photo de la facture, sur son téléphone." },
    { icon: "assembly", title: "L'AG l'approuve", desc: "Jointe à la convocation, votée en tantièmes, au PV sous 48 h." },
  ],
  foundationKicker: "CE QUI TIENT L'ENSEMBLE",
  foundationTitle: "Trois règles que rien ne contourne",
  foundations: [
    {
      icon: "unlock",
      title: "Un journal inaltérable",
      desc: "Votes, notifications, paiements, changements de propriétaire : ces lignes ne s'effacent pas. Une correction crée une nouvelle écriture liée à la précédente.",
    },
    {
      icon: "check",
      title: "L'arithmétique au centime",
      desc: "Aucun montant en virgule flottante. La répartition aux tantièmes gère explicitement l'écart d'arrondi et l'attribue, elle ne le perd pas.",
    },
    {
      icon: "sms",
      title: "FR et AR dès le premier écran",
      desc: "Le produit est construit en propriétés logiques : l'arabe s'affiche de droite à gauche pour de vrai, y compris dans les documents générés.",
    },
  ],
};

export const tarifs: SiteContent["tarifs"] = {
  metaTitle: "Tarifs — le prix est sur cette page, TTC",
  metaDescription:
    "Un prix par lot et par mois, TTC, selon la catégorie du décret : Petit 8 MAD, Moyen 12 MAD, Grand 15 MAD — 5,60, 8,40 et 10,50 MAD avec la remise fondateur de 30 %. Cabinets de 10 à 7 MAD HT. Mise en service à prix fixe. Trente jours avec vos propres données.",
  crumb: "TARIFS",
  title: "Le prix est sur cette page. Pas derrière un formulaire.",
  lede: "Trente jours avec vos propres données, reprise faite par nous : si vous ne continuez pas, vous ne payez rien. Ensuite, un prix par lot et par mois, TTC, facturé à la copropriété — et voté une fois en AG. Remise fondateur de 30 % pour les 100 premières résidences, jusqu'au 31 mars 2027.",
  facts: [
    { k: "Essai", v: "30 jours avec vos données" },
    { k: "Prix", v: "TTC, par lot et par mois" },
    { k: "Remise fondateur", v: "−30 % jusqu'au 31 mars 2027" },
    { k: "Résidents", v: "jamais facturés" },
  ],
  catalogueLabel: "Prix catalogue",
  netLabel: "Remise fondateur −30 %",
  setupLabel: "Mise en service",
  plans: [
    {
      key: "petit",
      name: "Petit",
      scope: "Charges ≤ 200 000 MAD / an",
      profile: "Moins de 30 lots · sans gardien",
      amount: "8",
      netAmount: "5,60",
      unit: "MAD / lot / mois",
      floorLabel: "à partir de 149 MAD / mois",
      billing: "Facturation annuelle · 1 788 MAD / an minimum · mensuel possible à +15 %",
      annexes: "Annexes 10, 13-1 et 13-2 — et les 12 si vous les voulez",
      example: "14 lots → 149 MAD par mois, le plancher",
      setup: "Import autonome inclus · accompagnée par nous : 990 MAD, prix fixe",
      features: [
        "Comptabilité et annexes",
        "Appels de fonds, quittances, relances",
        "Assemblées et PV",
        "Application résidents",
        "Reprise faite par nous pendant vos 30 jours",
      ],
      cta: { href: "/demo", label: "Commencer l'essai" },
    },
    {
      key: "moyen",
      name: "Moyen",
      scope: "Charges 200 000 – 500 000 MAD / an",
      profile: "30 à 120 lots · gardien",
      amount: "12",
      netAmount: "8,40",
      unit: "MAD / lot / mois",
      floorLabel: "à partir de 390 MAD / mois",
      billing: "Facturation annuelle · mensuel possible à +15 %",
      annexes: "Annexes 10, 11 et 12 — et les 12 si vous les voulez",
      example: "48 lots → 403,20 MAD par mois, soit 4 838 MAD par an",
      callout: "Pour une résidence de 48 lots, cela revient à moins d'un mois de salaire du gardien par an.",
      setup: "Import autonome inclus · accompagnée par nous : 2 490 MAD, prix fixe",
      option: {
        title: "Option Accompagné",
        amount: "18",
        netAmount: "12,60",
        unit: "MAD / lot / mois",
        desc: "Clôture annuelle faite par SyndicUp, kit AG, point mensuel de 30 min, WhatsApp prioritaire.",
        limited: "Places limitées",
      },
      features: [
        "Tout le plan Petit",
        "Écran de loge pour le gardien",
        "Recouvrement gradué, échéanciers",
        "Contrats, assurances, parkings",
        "Option Accompagné disponible",
      ],
      cta: { href: "/demo", label: "Commencer l'essai" },
      featured: true,
      badge: "LE PLUS CHOISI",
    },
    {
      key: "grand",
      name: "Grand",
      scope: "Charges ≥ 500 000 MAD / an",
      profile: "Plus de 120 lots · personnel",
      amount: "15",
      netAmount: "10,50",
      unit: "MAD / lot / mois",
      floorLabel: "à partir de 990 MAD / mois",
      billing: "Facturation annuelle · mensuel possible à +15 %",
      annexes: "Annexes 3 à 10, générées depuis les écritures",
      example: "110 lots → 1 155 MAD par mois",
      setup: "Mise en service accompagnée incluse, toujours faite par nous",
      option: {
        title: "Option Accompagné",
        amount: "22,50",
        netAmount: "15,75",
        unit: "MAD / lot / mois",
        desc: "Clôture annuelle faite par SyndicUp, kit AG, point mensuel de 30 min, WhatsApp prioritaire.",
        limited: "Places limitées",
      },
      features: [
        "Tout le plan Moyen",
        "RH et paie du personnel",
        "Location courte durée",
        "Rapport de gestion annuel",
        "Option Accompagné disponible",
      ],
      cta: { href: "/demo", label: "Commencer l'essai" },
    },
    {
      key: "cabinet",
      name: "Cabinet",
      scope: "Syndic professionnel, 3 mandats ou plus",
      profile: "Cabinet · 3 mandats ou plus",
      amount: "10 → 7",
      netAmount: "7 → 4,90",
      unit: "MAD HT / lot / mois",
      floorLabel: "minimum 12 000 MAD HT / an",
      billing: "Contrat annuel · facturation trimestrielle · devis en 24 h",
      annexes: "Toutes les annexes, pour chaque résidence du portefeuille",
      example: "800 lots → 4 480 MAD HT par mois au tarif fondateur",
      setup: "490 MAD HT par résidence, offerte à partir de la 10e",
      features: [
        "Tout le plan Grand, pour chaque résidence",
        "Vue portefeuille et alertes",
        "Permissions par gestionnaire",
        "Application au nom du cabinet",
        "Reprise du portefeuille par vagues",
      ],
      cta: { href: "/contact", label: "Demander un devis" },
    },
  ],
  ttcNote: "Prix TTC pour les copropriétés, HT pour les cabinets. Facturation annuelle par défaut, payable par virement ou chèque à 30 jours, au syndicat des copropriétaires ou au cabinet. Vous ne savez pas quel plan est le vôtre ? Le calculateur vous le dit en trente secondes.",
  whichPlan: "Quel plan pour ma copropriété ?",
  setupKicker: "MISE EN SERVICE",
  setupTitle: "Deux chemins, des prix fixes",
  setupLede: "Prix fixe, faite par nous, jamais facturée à l'heure. Quand vous choisissez la mise en service accompagnée, elle est facturée avec votre première facture annuelle, à la conversion — jamais avant.",
  setupPaths: [
    {
      icon: "upload",
      title: "Import autonome",
      price: "Inclus sur Petit et Moyen",
      desc: "Vous importez vos lots, tantièmes, propriétaires et soldes d'ouverture depuis le produit, guidé écran par écran, avec le fichier repris pendant vos 30 jours. Vous validez ligne à ligne.",
    },
    {
      icon: "review",
      title: "Mise en service accompagnée",
      price: "Prix fixe, faite par nous",
      desc: "Nous faisons tout : reprise, plan comptable, clés de répartition, soldes d'ouverture, invitations des résidents — et une vérification avant votre première clôture. Jamais facturée à l'heure, quel que soit l'état de votre fichier.",
    },
  ],
  setupPrices: [
    { plan: "Petit", price: "990 MAD", note: "prix fixe, ou import autonome inclus" },
    { plan: "Moyen", price: "2 490 MAD", note: "prix fixe, ou import autonome inclus" },
    { plan: "Grand", price: "Incluse", note: "toujours faite par nous" },
    { plan: "Cabinet", price: "490 MAD HT", note: "par résidence, offerte à partir de la 10e" },
  ],
  optionKicker: "OPTION ACCOMPAGNÉ",
  optionTitle: "Sur Moyen et Grand : nous faisons la clôture avec vous",
  optionLede: "+50 % du prix catalogue. Le nombre de places est limité : chaque résidence accompagnée a une personne nommée, pas un centre d'appels.",
  optionIncludes: [
    "Clôture annuelle faite par SyndicUp : annexes produites et vérifiées",
    "Kit AG : convocation, ordre du jour, PV, quorum",
    "Point mensuel de 30 minutes",
    "WhatsApp prioritaire avec une personne nommée",
  ],
  optionPrices: [
    { plan: "Moyen", amount: "18", netAmount: "12,60", unit: "MAD / lot / mois" },
    { plan: "Grand", amount: "22,50", netAmount: "15,75", unit: "MAD / lot / mois" },
  ],
  optionLimited: "Nombre de places limité",
  billingKicker: "FACTURATION",
  billingTitle: "Comment vous payez",
  billingRules: [
    {
      icon: "bank",
      title: "Annuelle par défaut",
      desc: "Payable par virement ou chèque à 30 jours, facturée à la copropriété — au syndicat des copropriétaires — ou au cabinet. Mensuel possible à +15 %.",
    },
    {
      icon: "gift",
      title: "Remise fondateur de 30 %",
      desc: "Pour les 100 premières résidences ou jusqu'au 31 mars 2027. Prix garanti 24 mois pour celles qui la prennent.",
    },
    {
      icon: "building",
      title: "Cabinets",
      desc: "Facturation trimestrielle, prix HT, contrat annuel. Devis en 24 h.",
    },
  ],
  cabinetKicker: "CABINETS",
  cabinetTitle: "Dégressif sur tout le portefeuille, prix HT",
  cabinetLede: "Dès qu'un seuil est franchi, le nouveau tarif s'applique à l'ensemble des lots sous mandat — pas seulement aux lots au-delà du seuil. Contrat annuel, minimum 12 000 MAD HT par an, facturation trimestrielle, devis en 24 h.",
  cabinetTiers: [
    { range: "1 à 499 lots", rate: "10 MAD HT / lot / mois · fondateur 7" },
    { range: "500 à 1 999 lots", rate: "8 MAD HT / lot / mois · fondateur 5,60" },
    { range: "2 000 lots et plus", rate: "7 MAD HT / lot / mois · fondateur 4,90" },
  ],
  cabinetMath: {
    title: "Le calcul qui compte pour un cabinet",
    lines: [
      "Un gestionnaire à 6 000 MAD / mois qui reprend 15 mandats de 40 lots, c'est 600 lots de plus.",
      "À 30 MAD de l'honoraire par lot, ce sont 18 000 MAD de revenus mensuels supplémentaires.",
      "La facture SyndicUp pour ces 600 lots : 4 800 MAD HT par mois au catalogue, 3 360 MAD HT au tarif fondateur.",
    ],
    result: "Le logiciel se paie sur le premier mandat repris. Les quatorze autres sont de la marge.",
  },
  trialKicker: "L'ESSAI",
  trialTitle: "30 jours avec vos propres données. Nous faisons la reprise. Si vous ne continuez pas, vous ne payez rien.",
  trialLede: "L'essai n'est pas une visite : il se fait sur votre copropriété, et il se termine par un document que vous ne pouvez pas produire seul.",
  trialSteps: [
    { icon: "mobile", title: "Vous vous inscrivez par SMS", desc: "Un code, pas de carte bancaire, pas de mot de passe." },
    { icon: "upload", title: "Nous reprenons vos données sous 48 h", desc: "Lots, tantièmes, propriétaires, soldes d'ouverture. Vous validez ligne à ligne." },
    { icon: "bank", title: "Vous émettez votre premier appel de fonds", desc: "Réparti aux tantièmes, envoyé, tracé — pendant l'essai." },
    { icon: "review", title: "Vous recevez votre annexe 10", desc: "Le vingt-cinquième jour, la version que vous présenterez à l'AG. Pour continuer, vous choisissez votre plan ; la mise en service accompagnée, si vous la prenez, est facturée avec la première facture annuelle — jamais avant." },
  ],
  founderKicker: "TARIF FONDATEUR",
  founderTitle: "−30 % pour les 100 premières résidences, jusqu'au 31 mars 2027",
  founderBody: "Le prix catalogue est affiché ; la remise fondateur de 30 % s'applique aux 100 premières résidences ou jusqu'au 31 mars 2027, et le prix est garanti 24 mois pour celles qui la prennent. En échange : un témoignage et un appel de référence quand un autre syndic voudra vous parler.",
  founderPoints: [
    "−30 % sur le prix catalogue, garanti 24 mois",
    "Petit 5,60 · Moyen 8,40 · Grand 10,50 MAD par lot et par mois",
    "Cabinets : 7 → 5,60 → 4,90 MAD HT, dès le premier jour du pilote",
    "Le tarif public est affiché : personne n'est surpris par une facture",
  ],
  founderCta: { href: "/demo", label: "Réserver ma place" },
  referralTitle: "Parrainage",
  referralBody: "Le syndic qui amène une autre résidence gagne deux mois crédités ; la nouvelle résidence gagne un mois d'essai de plus. Le syndic de l'immeuble A connaît celui de l'immeuble B — c'est comme ça que ça se passe.",
  addonsKicker: "OPTIONS",
  addonsTitle: "Ce qui a un coût réel, et ce que ça coûte",
  addons: [
    { icon: "sms", title: "SMS", price: "2 par lot et par mois inclus", desc: "Assez pour l'appel de fonds et une relance. Au-delà : 500 SMS pour 175 MAD, 2 000 pour 600 MAD. E-mail et notifications illimités." },
    { icon: "card", title: "Paiement en ligne", price: "1,5 % par transaction, minimum 2 MAD", desc: "Dès l'ouverture du paiement par carte : aucun abonnement, des frais d'encaissement à la transaction, portés par la copropriété." },
    { icon: "excel", title: "Reprise des exercices passés", price: "490 MAD par exercice", desc: "La reprise de l'exercice en cours est comprise. Chaque exercice antérieur repris et rapproché est facturé une fois." },
    { icon: "building", title: "Modules Moyen sur un plan Petit", price: "49 MAD / mois par module", desc: "Loge du gardien, location courte durée, contrats, parkings : à l'unité, si un petit immeuble en a besoin." },
  ],
  neverBilledKicker: "JAMAIS FACTURÉ",
  neverBilledTitle: "Ce qui reste gratuit, quel que soit le plan",
  neverBilled: [
    { icon: "mobile", title: "Les comptes résidents", desc: "Propriétaires, locataires, MRE : illimités. Le résident ne paie jamais." },
    { icon: "upload", title: "La reprise de l'exercice en cours", desc: "Lots, tantièmes, propriétaires, soldes d'ouverture, faite par nous." },
    { icon: "check", title: "L'import autonome", desc: "Paramétrage guidé, clés de répartition, invitations des résidents, depuis le produit. La mise en service accompagnée, elle, est à prix fixe." },
    { icon: "unlock", title: "La sortie", desc: "Export complet — écritures, pièces, PV — à tout moment, sans négociation. Après l'essai, vos données restent lisibles ; rien n'est supprimé." },
  ],
  compareKicker: "LIGNE À LIGNE",
  compareTitle: "Ce que chaque plan comprend",
  compareRows: [
    { feature: "Comptabilité et annexes générées", cells: [true, true, true, true] },
    { feature: "Appels de fonds, quittances, relances", cells: [true, true, true, true] },
    { feature: "Assemblées : convocation, quorum, PV", cells: [true, true, true, true] },
    { feature: "Dépenses avec justificatif obligatoire", cells: [true, true, true, true] },
    { feature: "Application résidents (iOS, Android, web)", cells: [true, true, true, true] },
    { feature: "Écran de loge pour le gardien", cells: ["Option", true, true, true] },
    { feature: "Recouvrement gradué, échéanciers", cells: ["—", true, true, true] },
    { feature: "Contrats, assurances, parkings", cells: ["Option", true, true, true] },
    { feature: "Location courte durée", cells: ["Option", true, true, true] },
    { feature: "RH et paie du personnel", cells: ["—", "—", true, true] },
    { feature: "Rapport de gestion annuel", cells: ["—", "—", true, true] },
    { feature: "Vue portefeuille, permissions par gestionnaire", cells: ["—", "—", "—", true] },
    { feature: "Documents et application au nom du cabinet", cells: ["—", "—", "—", true] },
    { feature: "SMS inclus par lot et par mois", cells: ["2", "2", "2", "2"] },
    { feature: "Reprise de l'exercice en cours", cells: ["Comprise", "Comprise", "Comprise", "Par vagues, comprise"] },
    { feature: "Mise en service", cells: ["Import inclus · accompagnée 990 MAD", "Import inclus · accompagnée 2 490 MAD", "Accompagnée incluse", "490 MAD HT / résidence, offerte dès la 10e"] },
    { feature: "Option Accompagné (+50 %)", cells: ["—", "18 MAD / lot (12,60 fondateur)", "22,50 MAD / lot (15,75 fondateur)", "—"] },
    { feature: "Support", cells: ["WhatsApp", "WhatsApp · Accompagné en option", "WhatsApp · Accompagné en option", "Interlocuteur nommé"] },
    { feature: "Facturation", cells: ["Annuelle (mensuelle +15 %)", "Annuelle (mensuelle +15 %)", "Annuelle (mensuelle +15 %)", "Trimestrielle, HT, contrat annuel"] },
    { feature: "Minimum", cells: ["149 MAD / mois", "390 MAD / mois", "990 MAD / mois", "12 000 MAD HT / an"] },
    { feature: "Export complet à la sortie", cells: [true, true, true, true] },
  ],
  resolutionKicker: "POUR VOTRE AG",
  resolutionTitle: "La résolution, déjà rédigée",
  resolutionBody: "Le vrai obstacle d'un syndic bénévole, c'est de se lever en assemblée et de proposer une dépense. Voici le texte ; le produit le pré-remplit avec vos chiffres, un clic avant l'AG.",
  resolutionText: "Résolution n° [X] — Adoption d'un outil de gestion. L'assemblée générale approuve l'abonnement à la plateforme SyndicUp pour la tenue de la comptabilité conformément au Décret 2.23.700, la production des annexes réglementaires, la gestion des appels de fonds et des assemblées, pour un montant annuel de [4 838] MAD TTC, soit [1,5] % du budget, imputé aux frais d'administration. Adoptée à la majorité de [ ] tantièmes.",
  faqKicker: "QUESTIONS SUR LE PRIX",
  faqTitle: "Ce qu'on nous demande avant de signer",
  faq: [
    {
      q: "Y a-t-il un essai gratuit ?",
      a: "30 jours avec vos propres données. Nous faisons la reprise. Si vous ne continuez pas, vous ne payez rien. Si vous continuez, vous choisissez votre plan ; la mise en service accompagnée, si vous la prenez, est facturée avec la première facture annuelle — jamais avant. Vos données restent lisibles dans tous les cas : rien n'est supprimé.",
    },
    {
      q: "Pourquoi n'y a-t-il plus de plan gratuit ?",
      a: "Parce qu'un logiciel gratuit sans limite de durée ne peut pas payer l'hébergement, le support ni la personne qui reprend votre fichier. Nous préférons un essai complet, un tarif public, et des résidents qui ne paient jamais — plutôt qu'une gratuité qui finit par un service dégradé.",
    },
    {
      q: "Pourquoi une mise en service payante ?",
      a: "Parce que nous la faisons nous-mêmes, à prix fixe, et que c'est ce qui garantit que votre première clôture sort juste. L'import autonome reste inclus.",
    },
    {
      q: "Qu'est-ce que l'option Accompagné ?",
      a: "Sur Moyen et Grand, pour +50 % du prix catalogue (Moyen 18 MAD, Grand 22,50 MAD par lot et par mois ; 12,60 et 15,75 au tarif fondateur) : la clôture annuelle faite par SyndicUp, annexes produites et vérifiées, le kit AG — convocation, ordre du jour, PV, quorum —, un point mensuel de 30 minutes et un WhatsApp prioritaire avec une personne nommée. Le nombre de places est limité.",
    },
    {
      q: "Qui paie, et comment ?",
      a: "La copropriété, comme charge d'administration votée en AG. La facture est établie TTC au nom du syndicat des copropriétaires, avec les mentions nécessaires pour être comptabilisée. Facturation annuelle par défaut, payable par virement ou chèque à 30 jours ; mensuel possible à +15 %. Pour un cabinet : facturation trimestrielle, prix HT, devis en 24 h.",
    },
    {
      q: "Quel plan est le nôtre ?",
      a: "Cela dépend de vos charges appelées annuelles, pas du nombre de lots : jusqu'à 200 000 MAD, Petit ; de 200 000 à 500 000, Moyen ; au-delà, Grand. Entrez-les dans le calculateur : il vous donne votre plan et ce que SyndicUp représente dans votre budget.",
      link: { href: "/ressources/calculateur-categorie-copropriete", label: "Calculateur de catégorie" },
    },
    {
      q: "Pourquoi un minimum mensuel ?",
      a: "Un immeuble de 12 lots coûte autant à accompagner qu'un immeuble de 60. Le minimum de 149 MAD couvre ce temps ; pour cet immeuble, cela revient à un peu plus de 12 MAD par lot — le prix d'un café.",
    },
    {
      q: "Pourquoi facturer à l'année ?",
      a: "Parce que c'est ainsi qu'une copropriété décide et paie : une fois, à l'AG, sur le budget voté. « 4 838 MAD par an pour toute la copropriété » est une phrase qu'un syndic peut porter en assemblée. Le mensuel reste possible, à +15 %.",
    },
    {
      q: "Comment fonctionne la remise fondateur ?",
      a: "30 % sur le prix catalogue, pour les 100 premières résidences ou jusqu'au 31 mars 2027, et le prix est garanti 24 mois pour celles qui la prennent. Petit 5,60, Moyen 8,40, Grand 10,50 MAD par lot et par mois ; les planchers ne bougent pas.",
    },
    {
      q: "Le tarif peut-il augmenter ?",
      a: "Pas sans préavis, jamais en cours de période, et jamais pour les résidences au tarif fondateur pendant leurs 24 mois. Toute évolution est annoncée 90 jours à l'avance et le tarif public reste affiché ici.",
    },
    {
      q: "Que se passe-t-il si nous changeons de catégorie ?",
      a: "Le plan suit vos charges appelées, à la clôture de l'exercice. Rien ne change dans le produit ni dans vos données : seule la facture de l'année suivante est ajustée, et vous en êtes prévenus avant l'AG.",
    },
    {
      q: "Comment un cabinet accède-t-il au tarif Cabinet ?",
      a: "Avec au moins trois mandats actifs, vérifiés à la mise en service. Le cabinet commence par un pilote de 90 jours sur trois résidences, reprise faite par nous, au tarif fondateur dès le premier jour. Prix HT, contrat annuel, minimum 12 000 MAD HT par an, devis en 24 h.",
      link: { href: "/pour-cabinet-syndic", label: "Pour cabinet de syndic" },
    },
    {
      q: "Et si nous arrêtons ?",
      a: "Vous exportez tout — écritures, pièces jointes, PV, journal — à tout moment, sans frais. Sans engagement de durée au-delà de la période facturée.",
    },
  ],
};

export const demo: SiteContent["demo"] = {
  metaTitle: "Réserver une démo",
  metaDescription:
    "Une démonstration de 20 minutes, en français ou en arabe, sur une résidence complète : comptabilité, annexes, AG et son PV. Trois champs, la suite sur WhatsApp.",
  crumb: "DÉMO",
  title: "Vingt minutes qui montrent, au lieu de promettre.",
  lede: "La démonstration se fait sur une résidence complète, pas sur des écrans vides : la comptabilité d'un exercice, les 12 annexes, une AG passée avec son PV, des incidents en cours. En français ou en arabe — et sur votre propre cas si vous nous envoyez votre fichier avant.",
  stepsKicker: "LE DÉROULÉ",
  stepsTitle: "Vingt minutes, quatre temps",
  steps: [
    { icon: "upload", title: "Votre fichier, si vous l'avez envoyé", desc: "La démo se fait alors sur votre copropriété, pas sur la nôtre." },
    { icon: "excel", title: "La comptabilité et les annexes", desc: "Un exercice complet, la clôture, les 12 états générés." },
    { icon: "assembly", title: "Une AG passée, avec son PV", desc: "Convocation tracée, quorum, votes en tantièmes, PV sous 48 h." },
    { icon: "whatsapp", title: "Le récapitulatif sur WhatsApp", desc: "Ce que vous avez vu, ce qu'il reste à décider, et la suite si vous la voulez." },
  ],
  inspectTitle: "CE QUE VOUS VERREZ PENDANT LA DÉMO",
  inspect: [
    "Une Annexe 10 réelle, avec ses lignes traçables jusqu'à la facture.",
    "Un PV d'AG horodaté, feuille de présence et pouvoirs inclus.",
    "Un lot en impayé, avec l'historique complet des relances.",
    "La même résidence en arabe, de droite à gauche.",
  ],
  formTitle: "Réserver une démo de 20 minutes",
  formLede: "Quatre champs. La suite se fait sur WhatsApp, à l'heure qui vous arrange.",
  fields: { name: "Nom", email: "E-mail", phone: "Téléphone", lots: "Nombre de lots" },
  placeholders: {
    name: "Nom et prénom",
    email: "vous@residence.ma",
    phone: "+212 6 00 00 00 00",
    lots: "48",
  },
  languageLabel: "Langue :",
  languageFr: "Français",
  languageAr: "العربية",
  submit: "Réserver",
  formNote:
    "Nous n'appelons pas sans prévenir. Vous recevez un message WhatsApp, vous choisissez le créneau.",
  formSent: "Message prêt sur WhatsApp — il ne reste qu'à l'envoyer.",
};

export const securite: SiteContent["securite"] = {
  metaTitle: "Sécurité & protection des données",
  metaDescription:
    "Cloisonnement appliqué dans l'application et dans la base (RLS), chiffrement en transit et au repos, sauvegardes restaurées pour de vrai, traitement déclaré à la CNDP.",
  crumb: "SÉCURITÉ",
  title: "Deux couches d'isolation, aucune confiance accordée à l'autre.",
  lede: "Le cloisonnement entre copropriétés est appliqué deux fois : dans l'application, et dans la base de données elle-même. Les deux doivent être vraies en même temps — l'une n'est jamais une excuse pour relâcher l'autre.",
  facts: [
    { k: "Hébergement", v: "Union européenne" },
    { k: "Chiffrement", v: "en transit et au repos" },
    { k: "Cloisonnement", v: "applicatif + base (RLS)" },
    { k: "CNDP", v: "traitement déclaré" },
  ],
  principlesKicker: "QUATRE PRINCIPES",
  principlesTitle: "Ce que nous nous interdisons",
  principles: [
    { icon: "unlock", title: "Aucune requête ne franchit une copropriété", desc: "La base refuse elle-même une lecture hors périmètre, même en cas d'erreur dans l'application." },
    { icon: "review", title: "Aucune action sans auteur ni date", desc: "Votes, paiements, notifications, changements de propriétaire : horodatés, nominatifs, inaltérables." },
    { icon: "building", title: "Aucune donnée que vous ne puissiez reprendre", desc: "Export complet — écritures, pièces, PV — à tout moment, jamais facturé." },
    { icon: "check", title: "Aucune sauvegarde non restaurée", desc: "Une sauvegarde qui n'a pas été restaurée n'existe pas : la restauration est testée, pas supposée." },
  ],
  blocksTitle: "Quatre couches, dans l'ordre",
  blocksLede: "De la ligne en base jusqu'au registre de la CNDP : ce qui protège vos données, et comment nous le vérifions.",
  blocks: [
    {
      step: "01 · ISOLATION",
      heading: "Row Level Security au niveau de la base",
      body: "L'identifiant de copropriété est extrait du jeton de session, jamais d'un paramètre envoyé par le client. Une politique Postgres est posée sur chaque table métier : même en cas de bug applicatif, une requête ne franchit pas la frontière d'une résidence.",
      points: [
        "Politiques RLS écrites table par table, testées.",
        "Aucun accès direct à la base depuis le web ou le mobile.",
        "Matrice de permissions par rôle : syndic, conseil, gardien, copropriétaire, locataire.",
      ],
    },
    {
      step: "02 · CHIFFREMENT",
      heading: "Chiffré en transit et au repos",
      body: "TLS obligatoire, chiffrement du stockage, documents servis par URL signée à durée limitée. Une facture jointe à une dépense n'est jamais accessible par une adresse devinable.",
      points: [
        "Bucket documents privé, URL signée 15 minutes.",
        "Connexion par code à usage unique, sans mot de passe stocké.",
        "Aucune donnée personnelle en clair dans les journaux techniques.",
      ],
    },
    {
      step: "03 · SAUVEGARDES",
      heading: "Restauration testée, pas supposée",
      body: "Sauvegardes quotidiennes avec restauration à un instant donné, et un exercice de restauration réel effectué périodiquement. Une sauvegarde qu'on n'a jamais restaurée n'est pas une sauvegarde.",
      points: [
        "Tables à valeur probante en écriture seule : pas d'UPDATE, pas de DELETE.",
        "Journal d'audit horodaté sur toute action financière ou probante.",
        "Export complet de vos données à la demande, sans négociation.",
      ],
    },
    {
      step: "04 · CNDP",
      heading: "Traitement déclaré, durées de conservation définies",
      body: "Le traitement des données des copropriétaires et locataires est déclaré à la Commission Nationale de contrôle de la protection des Données à caractère Personnel. Les durées de conservation sont écrites, et l'anonymisation à l'échéance est automatique — pas un geste manuel qu'on oublie.",
      points: [
        "Droit d'accès et de rectification outillés dans le produit.",
        "Anonymisation automatique après la durée légale de conservation.",
        "Sous-traitants listés, hébergement européen.",
      ],
      tinted: true,
    },
  ],
  rolesKicker: "QUI VOIT QUOI",
  rolesTitle: "Les permissions, rôle par rôle",
  rolesLede: "Attribuées par résidence et par rôle. Ce qu'un rôle ne voit pas n'est pas masqué : il n'est pas servi.",
  roles: [
    { role: "Syndic", sees: "Tout, sur ses résidences : comptes, lots, dépenses, assemblées, journal.", never: "Le portefeuille d'un autre gestionnaire." },
    { role: "Conseil syndical", sees: "Les comptes en lecture, la file de validation au-dessus du seuil, les PV.", never: "La modification d'une écriture." },
    { role: "Gardien", sees: "Incidents, petite caisse, relevés, rondes — sa loge.", never: "Les comptes, les soldes des lots, les données des résidents." },
    { role: "Copropriétaire", sees: "Son lot, ses quittances, les charges communes jusqu'à la facture.", never: "Le solde ou les données d'un autre lot." },
    { role: "Locataire", sees: "Les incidents, les informations pratiques de son occupation.", never: "Les comptes et les soldes." },
    { role: "Lecture seule", sees: "Ce qu'on lui ouvre, sans rien modifier — commissaire, avocat, auditeur.", never: "Une écriture, un vote, un paiement." },
  ],
  faqKicker: "QUESTIONS SUR LA SÉCURITÉ",
  faqTitle: "Ce que demandent les conseils syndicaux",
  faq: [
    { q: "Où sont physiquement les serveurs ?", a: "Dans l'Union européenne, chez un hébergeur soumis au RGPD, avec sauvegardes chiffrées dans une seconde région. Le traitement est déclaré à la CNDP." },
    { q: "Qui, chez SyndicUp, peut lire nos données ?", a: "Personne en routine. Les accès de maintenance sont nominatifs, journalisés et limités dans le temps ; ils sont ouverts à votre demande ou en cas d'incident, et vous en êtes informés." },
    { q: "Que se passe-t-il si nous quittons SyndicUp ?", a: "Vous exportez tout — écritures, pièces jointes, PV, journal — dans un format lisible. C'est inclus, à tout moment, sans négociation." },
    { q: "Les factures et PV sont-ils accessibles par une URL publique ?", a: "Non. Chaque pièce est servie par une URL signée, à durée limitée, générée pour un utilisateur autorisé." },
  ],
};

export const ressources: SiteContent["ressources"] = {
  metaTitle: "Ressources — guides, modèles et outils",
  metaDescription:
    "Guides du Décret 2.23.700, explication des 12 annexes, checklist de clôture, modèles de convocation et de PV, calculateur de catégorie. En accès libre, FR et AR.",
  crumb: "RESSOURCES",
  title: "Ce que la loi demande, expliqué par ceux qui l'ont codé.",
  lede: "Guides, modèles et outils, en accès libre. Utiles même si vous ne devenez jamais client.",
  pillarKicker: "GUIDE PILIER · MIS À JOUR SEPT. 2026",
  pillarTitle: "Le Décret 2.23.700, lu ligne par ligne pour un syndic",
  pillarBody:
    "Ce que le texte exige vraiment, dans quel ordre, avec quelles échéances — et ce qui reste à faire confirmer par un juriste.",
  pillarCta: "Lire le guide →",
  pillarImage: "/images/residence-hero.jpg",
  pillarImageAlt: "Façade d'une résidence en copropriété",
  cards: [
    {
      href: "/ressources/les-12-annexes-expliquees",
      kicker: "GUIDE",
      title: "Les 12 annexes expliquées",
      desc: "À quoi sert chaque état comptable, qui le lit, et ce qui le rend contestable.",
      image: "/images/residence-courtyard.jpg",
      imageAlt: "Cour intérieure d'une résidence",
      tone: "plain",
    },
    {
      href: "/ressources/calculateur-categorie-copropriete",
      kicker: "OUTIL INTERACTIF",
      title: "Calculateur de catégorie",
      desc: "Entrez vos charges annuelles : vous obtenez votre catégorie, vos obligations et ce que SyndicUp représente dans votre budget.",
      tone: "tosca",
      tint: "tosca",
    },
    {
      href: "/ressources/checklist-cloture-2026",
      kicker: "CHECKLIST",
      title: "Clôture 2026",
      desc: "Les 14 gestes à faire avant votre AG, dans l'ordre, avec les délais.",
      image: "/images/residence-entrance.jpg",
      imageAlt: "Entrée d'une résidence",
      tone: "plain",
    },
    {
      href: "/ressources/modele-convocation-ag",
      kicker: "MODÈLE · FR & AR",
      title: "Convocation d'AG",
      desc: "Mentions obligatoires, ordre du jour, formulaire de pouvoir.",
      tone: "plain",
    },
    {
      href: "/ressources/modele-pv-ag",
      kicker: "MODÈLE · FR & AR",
      title: "PV d'assemblée générale",
      desc: "Structure complète : présence, pouvoirs, votes par tantièmes, contestations.",
      tone: "plain",
    },
    {
      kicker: "BLOG",
      title: "Notes de terrain",
      desc: "Ce qu'on apprend en accompagnant de vraies clôtures. Premier billet en octobre 2026.",
      tone: "dashed",
    },
  ],
};

export const calc: SiteContent["calc"] = {
  metaTitle: "Calculateur de catégorie et de coût",
  metaDescription:
    "Entrez vos charges appelées et votre nombre de lots : l'outil donne la catégorie de votre copropriété au sens du Décret 2.23.700, les annexes exigées, et le coût de SyndicUp en part du budget.",
  crumb: "CALCULATEUR",
  title: "Quelle catégorie, quelles annexes, et combien ça coûte ?",
  lede: "Le Décret 2.23.700 classe les copropriétés par charges appelées annuelles. Entrez les vôtres : l'outil affiche votre catégorie, les états à produire, et ce que SyndicUp représente dans votre budget.",
  lotsLabel: "Nombre de lots principaux",
  budgetLabel: "Charges appelées par an (MAD)",
  budgetHint: "Le budget voté en AG pour l'exercice — c'est ce chiffre qui décide de la catégorie.",
  commercialLabel: "Locaux commerciaux",
  cabinetLabel: "Vous êtes un cabinet (3 mandats ou plus)",
  setupLabel: "Mise en service accompagnée",
  setupHint: "Prix fixe, faite par nous. Incluse sur Grand ; import autonome inclus sur Petit et Moyen.",
  yes: "Oui",
  no: "Non",
  regimeKicker: "CATÉGORIE DU DÉCRET",
  dutiesKicker: "CE QUE VOUS DEVEZ PRODUIRE",
  planKicker: "VOTRE PLAN SYNDICUP",
  perLotLabel: "Charge moyenne par lot",
  priceLabel: "Abonnement",
  yearOneLabel: "Coût année 1",
  yearOneHint: "mise en service + 12 mois",
  yearTwoLabel: "À partir de l'année 2",
  shareLabel: "Part du budget",
  floorNote: "Le plancher du plan s'applique.",
  perYear: "MAD / an",
  perMonth: "MAD / mois",
  ofBudget: "du budget de la copropriété",
  founderNote: "Prix catalogue {catalogue} MAD / lot · remise fondateur −30 % jusqu'au 31 mars 2027, prix garanti 24 mois",
  setupIncludedNote: "Mise en service accompagnée incluse dans le plan Grand.",
  cabinetNote: "Prix HT, contrat annuel, minimum 12 000 MAD HT par an, facturation trimestrielle. Mise en service 490 MAD HT par résidence, offerte à partir de la 10e.",
  disclaimer:
    "Les seuils sont ceux du Décret 2.23.700 (charges appelées annuelles). La liste des états par catégorie suit notre lecture du texte et reste à confirmer avec votre conseil juridique ; l'outil ne remplace pas un avis d'avocat. Prix TTC pour les copropriétés, HT pour les cabinets, remise fondateur de 30 % appliquée.",
  regimes: {
    petit: {
      name: "Petite copropriété",
      summary: "Charges appelées jusqu'à 200 000 MAD par an. Tenue courante possible par un syndic bénévole, sans comptable dédié — à condition de saisir au fil de l'eau.",
      annexes: "Annexes 10, 13-1 et 13-2",
      duties: [
        "Annexe 10 : répartition des charges par lot.",
        "Annexes 13-1 et 13-2 : état simplifié des recettes et des dépenses.",
        "Budget prévisionnel voté chaque année.",
        "Justificatif conservé pour chaque dépense.",
        "AG annuelle d'approbation des comptes, PV distribué à tous.",
      ],
    },
    moyen: {
      name: "Copropriété moyenne",
      summary: "Charges appelées entre 200 000 et 500 000 MAD par an. Le volume d'écritures et le nombre d'interlocuteurs imposent une saisie au fil de l'eau et une répartition calculée.",
      annexes: "Annexes 10, 11 et 12",
      duties: [
        "Annexe 10 : répartition des charges par lot.",
        "Annexe 11 : état des créances et des dettes, avec ancienneté des impayés.",
        "Annexe 12 : situation de trésorerie rapprochée avec la banque.",
        "Budget prévisionnel voté, écart budget / réalisé expliqué.",
        "Validation à deux yeux des dépenses au-delà du seuil voté.",
      ],
    },
    grand: {
      name: "Grande copropriété",
      summary: "Charges appelées de 500 000 MAD par an et plus. Huit états, un contrôle plus attentif, souvent un commissaire aux comptes : seul un système intégré tient dans la durée.",
      annexes: "Annexes 3 à 10",
      duties: [
        "Annexes 3 à 10 : budget, réalisé, créances, dettes, trésorerie, provisions, répartition — avec justificatifs référencés ligne à ligne.",
        "Comptes revus par un professionnel avant présentation en AG.",
        "Fonds de travaux avec plan pluriannuel voté.",
        "Journal d'audit des actions financières, conservé.",
        "Registre des occupants tenu à jour.",
      ],
    },
  },
  commercialDuty: "Clés de répartition distinctes pour les locaux commerciaux.",
  cta: { href: "/tarifs", label: "Voir la grille complète" },
};

export const apropos: SiteContent["apropos"] = {
  metaTitle: "À propos",
  metaDescription:
    "SyndicUp est né d'une clôture d'exercice ratée. Nous construisons la comptabilité et sa preuve d'abord, les écrans ensuite.",
  crumb: "À PROPOS",
  title: "Nous avons commencé par lire le décret. Pas par dessiner des écrans.",
  lede: "SyndicUp est né d'une clôture d'exercice ratée dans une copropriété de 48 lots à Casablanca. Le tableur ne bouclait pas, l'AG a été contestée, et personne ne savait quelle annexe manquait. Nous avons lu le Décret 2.23.700 ligne par ligne, puis construit le produit qui l'applique.",
  principlesKicker: "CE QUI NOUS GUIDE",
  principlesTitle: "Trois principes, dans cet ordre",
  principles: [
    { icon: "review", title: "La preuve avant la promesse", desc: "Un PV opposable, une dépense avec sa pièce, un journal inaltérable : le produit produit des preuves, pas des tableaux de bord." },
    { icon: "gift", title: "Un prix qu'on peut porter en AG", desc: "Trente jours avec vos propres données, puis 1 à 3 % du budget d'une résidence, TTC, affiché publiquement. Le résident ne paie jamais." },
    { icon: "sms", title: "Dans les deux langues, pour de vrai", desc: "L'arabe se lit de droite à gauche jusque dans les documents générés. Ce n'est pas une traduction posée sur une interface française." },
  ],
  image: "/images/residence-courtyard.jpg",
  imageAlt: "Cour intérieure d'une résidence en copropriété",
  paras: [
    "SyndicUp est né d'une clôture d'exercice ratée. Un immeuble de 48 lots à Casablanca, un syndic bénévole consciencieux, trois classeurs, un tableur — et l'impossibilité de produire, en janvier, des comptes que personne n'avait tenus en mars.",
    "Le Décret 2.23.700 a changé la nature du problème. Il ne demande plus de la bonne volonté, il demande des documents. Un logiciel qui n'est pas capable de les produire depuis les écritures de l'année n'est pas un logiciel de syndic : c'est un cahier avec une interface.",
    "Nous construisons donc dans l'ordre inverse de l'habituel : d'abord la comptabilité et sa preuve, ensuite les écrans. Et nous publions ce que nous ne savons pas encore — les valeurs légales en attente de confirmation juridique sont documentées, pas devinées.",
  ],
  commitmentsTitle: "NOS ENGAGEMENTS",
  commitments: [
    "Aucun chiffre d'usage publié avant d'être vérifiable.",
    "Vos données sont exportables intégralement, à tout moment.",
    "Le tarif est public et ne dépend pas de votre capacité à négocier.",
    "Les résidents ne paient jamais, quel que soit le plan.",
  ],
  companyTitle: "SOCIÉTÉ",
  companyLines: [
    "SYNDICUP SARL",
    "Casablanca, Maroc",
    "RC 000000 · ICE 000000000000000",
    "contact@syndicup.ma",
  ],
};

export const contact: SiteContent["contact"] = {
  metaTitle: "Contact",
  metaDescription:
    "WhatsApp, reprise de données, cabinets et promoteurs, données personnelles — les bonnes adresses pour joindre SyndicUp, en français ou en arabe.",
  crumb: "CONTACT",
  title: "WhatsApp d'abord. C'est plus rapide pour vous.",
  lede: "Nous répondons pendant les heures ouvrables, en français ou en arabe. Si vous préférez le mail ou le téléphone, c'est en bas.",
  whatsappTitle: "WhatsApp",
  whatsappBody:
    "Message pré-rempli, réponse le jour même. Vous pouvez envoyer votre Excel directement.",
  cards: [
    {
      icon: "upload",
      title: "Reprise de données",
      body: "Envoyez votre fichier tel qu'il est — même incomplet, même avec des onglets par année. Nous vous renvoyons une reprise à valider.",
      email: "reprise@syndicup.ma",
    },
    {
      icon: "building",
      title: "Cabinets & promoteurs",
      body: "Portefeuille de plusieurs résidences, reprise groupée, interlocuteur nommé.",
      email: "cabinets@syndicup.ma",
    },
    {
      icon: "unlock",
      title: "Données personnelles",
      body: "Droit d'accès, de rectification, d'effacement. Réponse sous les délais légaux.",
      email: "donnees@syndicup.ma",
    },
  ],
  hoursKicker: "QUAND NOUS RÉPONDONS",
  hoursTitle: "Une personne, pas un centre d'appels",
  hours: [
    { k: "WhatsApp", v: "en général sous une heure, heures ouvrables" },
    { k: "E-mail", v: "sous 24 h ouvrées" },
    { k: "Reprise de données", v: "retour à valider sous 48 h" },
    { k: "Langues", v: "français, arabe" },
  ],
};
